language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE color_schemes_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: BDPuMvc6zxKz/1nAZL8vdeS6A9yz4VcL7PIngRT2lapTA/nVAHIGnZMa7zda7O33tu24KEKDjl84LEjwrmrSPK6fWx9712Z1PQkkEGn1NShJGmmVU57c7K2CZhZAP7pI7aqszZQdg2QSNZF2OYzAX+YRDVDb1vqNpa0uosAMgL9rzBFyKqNYESl2xaMxloH9vfQ8bkNBRe8WCdUjPB+YumleqzyqzVhsnTpOeFE4t65CY+WZhGFs6ZieaLfwjnDVtoIL8q6PkjKpbOu514wgGWpU/m5gYDfk4bLhfcB4iZ6W0/EtX8riLDU83xjdS/ApzC93dXAK5Usb1K20QN/2MJVpx/YwBULrTtCpDHZ/UCBSHJpo/IMBzUC1B4suQCBnv7VqmoRy6c0+XHCt9WLa8FtGXbz3yPdXxntZc9WIr5jBp50EzwleUJ8ZKIYvNmjGAeulSFqz4VXdjeDJ7NLYWUBBo4OFkMd9yGVnVWTK0SZXhvvsH5B4/dgzwHM17YpSHfsVs8D3hU0jvBEatyFmB7aZTg8PUpVpXEArEEQHh8lA81soIL3vRSWZort6PGnirnLNRHKDUl6kQOiVbtJNhnZ9xIt8v/pKa1RGygUvgP02p5ustRIEiiIOjf/f0IoeB/rVdly4nFZma6AEcAQCdt2Ejqqo59nP5OC36EC4vlQ=
  app: palettepicker-be
  on:
    repo: annekemcgrady/palettepicker_db
